CREATE TABLE estados (id_estado INTEGER AUTO_INCREMENT NOT NULL, descripcion_estado VARCHAR(255), PRIMARY KEY (id_estado))
CREATE TABLE proveedores (id_proveedor INTEGER AUTO_INCREMENT NOT NULL, direccion VARCHAR(255), nit_proveedor VARCHAR(255), nombre_empresa VARCHAR(255), representante_legal VARCHAR(255), telefono INTEGER, ciudades_id_ciudad INTEGER, PRIMARY KEY (id_proveedor))
CREATE TABLE areas (id_area INTEGER AUTO_INCREMENT NOT NULL, nombre_area VARCHAR(255), PRIMARY KEY (id_area))
CREATE TABLE roles (id_rol INTEGER AUTO_INCREMENT NOT NULL, estado INTEGER, nombre_rol VARCHAR(255), PRIMARY KEY (id_rol))
CREATE TABLE ciudades (id_ciudad INTEGER AUTO_INCREMENT NOT NULL, nombre_ciudad VARCHAR(255), PRIMARY KEY (id_ciudad))
CREATE TABLE permisos (id_permiso INTEGER AUTO_INCREMENT NOT NULL, estado INTEGER, icon VARCHAR(255), nombre_permiso VARCHAR(255), nombre_permiso_en VARCHAR(255), url LONGTEXT, permiso_padre INTEGER, PRIMARY KEY (id_permiso))
CREATE TABLE personas (id_persona INTEGER AUTO_INCREMENT NOT NULL, apellido VARCHAR(255), direccion VARCHAR(255), documento INTEGER, email VARCHAR(255), estado INTEGER, fecha_ingreso DATE, fecha_nacimiento DATE, imagen VARCHAR(255), nombre VARCHAR(255), password VARCHAR(255), telefono INTEGER, ultima_vez DATE, areas_id_area INTEGER, PRIMARY KEY (id_persona))
CREATE TABLE materias_prima (id_materia INTEGER AUTO_INCREMENT NOT NULL, calibre INTEGER, dimension_alto INTEGER, dimension_largo INTEGER, referencia VARCHAR(255), tipo_materia_prima VARCHAR(255), PRIMARY KEY (id_materia))
CREATE TABLE stocks (id_stock INTEGER AUTO_INCREMENT NOT NULL, fecha_actualizacion DATE, fecha_ingreso DATE, stock INTEGER, materias_prima_id_materia INTEGER, PRIMARY KEY (id_stock))
CREATE TABLE pedidos (id_pedido INTEGER AUTO_INCREMENT NOT NULL, cantidad INTEGER, correo_cliente VARCHAR(255), descripcion VARCHAR(255), esta_asignado INTEGER, nombre_cliente VARCHAR(255), nombre_proyecto VARCHAR(255), realizo_pago SMALLINT, telefono_cliente VARCHAR(255), materias_prima_id_materia INTEGER, vendedor_id_persona INTEGER, PRIMARY KEY (id_pedido))
CREATE TABLE dificultades (id_dificultad INTEGER AUTO_INCREMENT NOT NULL, descripcion_dificultad VARCHAR(255), PRIMARY KEY (id_dificultad))
CREATE TABLE detalle_pedidos (id_detalle INTEGER AUTO_INCREMENT NOT NULL, cantidad INTEGER, dimension_alto DOUBLE, dimension_ancho DOUBLE, pedidos_id_pedido INTEGER, PRIMARY KEY (id_detalle))
CREATE TABLE proyectos (id_proyecto INTEGER AUTO_INCREMENT NOT NULL, fecha_finalizado DATETIME, fecha_inicio DATETIME, tiempo_estimado DATETIME, dificultades_id_dificultad INTEGER, estados_id_estado INTEGER, operario_id_persona INTEGER, pedidos_id_pedido INTEGER, PRIMARY KEY (id_proyecto))
CREATE TABLE proveedores_materias_prima (proveedores_id_proveedor INTEGER NOT NULL, materias_prima_id_materia INTEGER NOT NULL, PRIMARY KEY (proveedores_id_proveedor, materias_prima_id_materia))
CREATE TABLE roles_permisos (roles_id_rol INTEGER NOT NULL, permisos_id_permiso INTEGER NOT NULL, PRIMARY KEY (roles_id_rol, permisos_id_permiso))
CREATE TABLE roles_personas (roles_id_rol INTEGER NOT NULL, personas_id_persona INTEGER NOT NULL, PRIMARY KEY (roles_id_rol, personas_id_persona))
ALTER TABLE proveedores ADD CONSTRAINT FK_proveedores_ciudades_id_ciudad FOREIGN KEY (ciudades_id_ciudad) REFERENCES ciudades (id_ciudad)
ALTER TABLE permisos ADD CONSTRAINT FK_permisos_permiso_padre FOREIGN KEY (permiso_padre) REFERENCES permisos (id_permiso)
ALTER TABLE personas ADD CONSTRAINT FK_personas_areas_id_area FOREIGN KEY (areas_id_area) REFERENCES areas (id_area)
ALTER TABLE stocks ADD CONSTRAINT FK_stocks_materias_prima_id_materia FOREIGN KEY (materias_prima_id_materia) REFERENCES materias_prima (id_materia)
ALTER TABLE pedidos ADD CONSTRAINT FK_pedidos_materias_prima_id_materia FOREIGN KEY (materias_prima_id_materia) REFERENCES materias_prima (id_materia)
ALTER TABLE pedidos ADD CONSTRAINT FK_pedidos_vendedor_id_persona FOREIGN KEY (vendedor_id_persona) REFERENCES personas (id_persona)
ALTER TABLE detalle_pedidos ADD CONSTRAINT FK_detalle_pedidos_pedidos_id_pedido FOREIGN KEY (pedidos_id_pedido) REFERENCES pedidos (id_pedido)
ALTER TABLE proyectos ADD CONSTRAINT FK_proyectos_estados_id_estado FOREIGN KEY (estados_id_estado) REFERENCES estados (id_estado)
ALTER TABLE proyectos ADD CONSTRAINT FK_proyectos_pedidos_id_pedido FOREIGN KEY (pedidos_id_pedido) REFERENCES pedidos (id_pedido)
ALTER TABLE proyectos ADD CONSTRAINT FK_proyectos_operario_id_persona FOREIGN KEY (operario_id_persona) REFERENCES personas (id_persona)
ALTER TABLE proyectos ADD CONSTRAINT FK_proyectos_dificultades_id_dificultad FOREIGN KEY (dificultades_id_dificultad) REFERENCES dificultades (id_dificultad)
ALTER TABLE proveedores_materias_prima ADD CONSTRAINT proveedores_materias_primaproveedores_id_proveedor FOREIGN KEY (proveedores_id_proveedor) REFERENCES proveedores (id_proveedor)
ALTER TABLE proveedores_materias_prima ADD CONSTRAINT proveedoresmaterias_primamaterias_prima_id_materia FOREIGN KEY (materias_prima_id_materia) REFERENCES materias_prima (id_materia)
ALTER TABLE roles_permisos ADD CONSTRAINT FK_roles_permisos_roles_id_rol FOREIGN KEY (roles_id_rol) REFERENCES roles (id_rol)
ALTER TABLE roles_permisos ADD CONSTRAINT FK_roles_permisos_permisos_id_permiso FOREIGN KEY (permisos_id_permiso) REFERENCES permisos (id_permiso)
ALTER TABLE roles_personas ADD CONSTRAINT FK_roles_personas_personas_id_persona FOREIGN KEY (personas_id_persona) REFERENCES personas (id_persona)
ALTER TABLE roles_personas ADD CONSTRAINT FK_roles_personas_roles_id_rol FOREIGN KEY (roles_id_rol) REFERENCES roles (id_rol)
